/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated/agentes'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedCuradoriaRouteImport } from './routes/_authenticated/curadoria'
import { Route as AuthenticatedDnaRouteImport } from './routes/_authenticated/dna'
import { Route as AuthenticatedPerfisRouteImport } from './routes/_authenticated/perfis'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingProcessandoRouteImport } from './routes/onboarding.processando'
import { Route as AuthenticatedAgentesIndexRouteImport } from './routes/_authenticated/agentes.index'
import { Route as AuthenticatedAgentesAgenteRouteImport } from './routes/_authenticated/agentes.$agente'
import { Route as AuthenticatedAprovacaoPautaIdRouteImport } from './routes/_authenticated/aprovacao.$pautaId'
import { Route as ApiPublicWebhooksKiwifyRouteImport } from './routes/api/public/webhooks/kiwify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuradoriaRoute = AuthenticatedCuradoriaRouteImport.update({
  id: '/curadoria',
  path: '/curadoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDnaRoute = AuthenticatedDnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfisRoute = AuthenticatedPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProcessandoRoute = OnboardingProcessandoRouteImport.update({
  id: '/processando',
  path: '/processando',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthenticatedAgentesIndexRoute =
  AuthenticatedAgentesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentesRoute,
  } as any)
const AuthenticatedAgentesAgenteRoute =
  AuthenticatedAgentesAgenteRouteImport.update({
    id: '/$agente',
    path: '/$agente',
    getParentRoute: () => AuthenticatedAgentesRoute,
  } as any)
const AuthenticatedAprovacaoPautaIdRoute =
  AuthenticatedAprovacaoPautaIdRouteImport.update({
    id: '/aprovacao/$pautaId',
    path: '/aprovacao/$pautaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksKiwifyRoute = ApiPublicWebhooksKiwifyRouteImport.update({
  id: '/api/public/webhooks/kiwify',
  path: '/api/public/webhooks/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agentes': typeof AuthenticatedAgentesRouteWithChildren
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/curadoria': typeof AuthenticatedCuradoriaRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/agentes/$agente': typeof AuthenticatedAgentesAgenteRoute
  '/aprovacao/$pautaId': typeof AuthenticatedAprovacaoPautaIdRoute
  '/agentes/': typeof AuthenticatedAgentesIndexRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/curadoria': typeof AuthenticatedCuradoriaRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/agentes/$agente': typeof AuthenticatedAgentesAgenteRoute
  '/aprovacao/$pautaId': typeof AuthenticatedAprovacaoPautaIdRoute
  '/agentes': typeof AuthenticatedAgentesIndexRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agentes': typeof AuthenticatedAgentesRouteWithChildren
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/curadoria': typeof AuthenticatedCuradoriaRoute
  '/_authenticated/dna': typeof AuthenticatedDnaRoute
  '/_authenticated/perfis': typeof AuthenticatedPerfisRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/onboarding/processando': typeof OnboardingProcessandoRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_authenticated/agentes/$agente': typeof AuthenticatedAgentesAgenteRoute
  '/_authenticated/aprovacao/$pautaId': typeof AuthenticatedAprovacaoPautaIdRoute
  '/_authenticated/agentes/': typeof AuthenticatedAgentesIndexRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/redefinir-senha'
    | '/admin'
    | '/agentes'
    | '/assinatura'
    | '/curadoria'
    | '/dna'
    | '/perfis'
    | '/pipeline'
    | '/onboarding/processando'
    | '/onboarding/'
    | '/agentes/$agente'
    | '/aprovacao/$pautaId'
    | '/agentes/'
    | '/api/public/webhooks/kiwify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/admin'
    | '/assinatura'
    | '/curadoria'
    | '/dna'
    | '/perfis'
    | '/pipeline'
    | '/onboarding/processando'
    | '/onboarding'
    | '/agentes/$agente'
    | '/aprovacao/$pautaId'
    | '/agentes'
    | '/api/public/webhooks/kiwify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/agentes'
    | '/_authenticated/assinatura'
    | '/_authenticated/curadoria'
    | '/_authenticated/dna'
    | '/_authenticated/perfis'
    | '/_authenticated/pipeline'
    | '/onboarding/processando'
    | '/onboarding/'
    | '/_authenticated/agentes/$agente'
    | '/_authenticated/aprovacao/$pautaId'
    | '/_authenticated/agentes/'
    | '/api/public/webhooks/kiwify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ApiPublicWebhooksKiwifyRoute: typeof ApiPublicWebhooksKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curadoria': {
      id: '/_authenticated/curadoria'
      path: '/curadoria'
      fullPath: '/curadoria'
      preLoaderRoute: typeof AuthenticatedCuradoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dna': {
      id: '/_authenticated/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof AuthenticatedDnaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfis': {
      id: '/_authenticated/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof AuthenticatedPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/processando': {
      id: '/onboarding/processando'
      path: '/processando'
      fullPath: '/onboarding/processando'
      preLoaderRoute: typeof OnboardingProcessandoRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_authenticated/agentes/': {
      id: '/_authenticated/agentes/'
      path: '/'
      fullPath: '/agentes/'
      preLoaderRoute: typeof AuthenticatedAgentesIndexRouteImport
      parentRoute: typeof AuthenticatedAgentesRoute
    }
    '/_authenticated/agentes/$agente': {
      id: '/_authenticated/agentes/$agente'
      path: '/$agente'
      fullPath: '/agentes/$agente'
      preLoaderRoute: typeof AuthenticatedAgentesAgenteRouteImport
      parentRoute: typeof AuthenticatedAgentesRoute
    }
    '/_authenticated/aprovacao/$pautaId': {
      id: '/_authenticated/aprovacao/$pautaId'
      path: '/aprovacao/$pautaId'
      fullPath: '/aprovacao/$pautaId'
      preLoaderRoute: typeof AuthenticatedAprovacaoPautaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/kiwify': {
      id: '/api/public/webhooks/kiwify'
      path: '/api/public/webhooks/kiwify'
      fullPath: '/api/public/webhooks/kiwify'
      preLoaderRoute: typeof ApiPublicWebhooksKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAgentesRouteChildren {
  AuthenticatedAgentesAgenteRoute: typeof AuthenticatedAgentesAgenteRoute
  AuthenticatedAgentesIndexRoute: typeof AuthenticatedAgentesIndexRoute
}

const AuthenticatedAgentesRouteChildren: AuthenticatedAgentesRouteChildren = {
  AuthenticatedAgentesAgenteRoute: AuthenticatedAgentesAgenteRoute,
  AuthenticatedAgentesIndexRoute: AuthenticatedAgentesIndexRoute,
}

const AuthenticatedAgentesRouteWithChildren =
  AuthenticatedAgentesRoute._addFileChildren(AuthenticatedAgentesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRouteWithChildren
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedCuradoriaRoute: typeof AuthenticatedCuradoriaRoute
  AuthenticatedDnaRoute: typeof AuthenticatedDnaRoute
  AuthenticatedPerfisRoute: typeof AuthenticatedPerfisRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedAprovacaoPautaIdRoute: typeof AuthenticatedAprovacaoPautaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgentesRoute: AuthenticatedAgentesRouteWithChildren,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedCuradoriaRoute: AuthenticatedCuradoriaRoute,
  AuthenticatedDnaRoute: AuthenticatedDnaRoute,
  AuthenticatedPerfisRoute: AuthenticatedPerfisRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedAprovacaoPautaIdRoute: AuthenticatedAprovacaoPautaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OnboardingRouteChildren {
  OnboardingProcessandoRoute: typeof OnboardingProcessandoRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingProcessandoRoute: OnboardingProcessandoRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ApiPublicWebhooksKiwifyRoute: ApiPublicWebhooksKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
