/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPerfisRouteImport } from './routes/_authenticated/perfis'
import { Route as AuthenticatedCuradoriaRouteImport } from './routes/_authenticated/curadoria'
import { Route as AuthenticatedAgentesRouteImport } from './routes/_authenticated/agentes'
import { Route as AuthenticatedAgentesIndexRouteImport } from './routes/_authenticated/agentes.index'
import { Route as AuthenticatedAprovacaoPautaIdRouteImport } from './routes/_authenticated/aprovacao.$pautaId'
import { Route as AuthenticatedAgentesAgenteRouteImport } from './routes/_authenticated/agentes.$agente'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfisRoute = AuthenticatedPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuradoriaRoute = AuthenticatedCuradoriaRouteImport.update({
  id: '/curadoria',
  path: '/curadoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentesRoute = AuthenticatedAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentesIndexRoute =
  AuthenticatedAgentesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentesRoute,
  } as any)
const AuthenticatedAprovacaoPautaIdRoute =
  AuthenticatedAprovacaoPautaIdRouteImport.update({
    id: '/aprovacao/$pautaId',
    path: '/aprovacao/$pautaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentesAgenteRoute =
  AuthenticatedAgentesAgenteRouteImport.update({
    id: '/$agente',
    path: '/$agente',
    getParentRoute: () => AuthenticatedAgentesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agentes': typeof AuthenticatedAgentesRouteWithChildren
  '/curadoria': typeof AuthenticatedCuradoriaRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/agentes/$agente': typeof AuthenticatedAgentesAgenteRoute
  '/aprovacao/$pautaId': typeof AuthenticatedAprovacaoPautaIdRoute
  '/agentes/': typeof AuthenticatedAgentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/curadoria': typeof AuthenticatedCuradoriaRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/agentes/$agente': typeof AuthenticatedAgentesAgenteRoute
  '/aprovacao/$pautaId': typeof AuthenticatedAprovacaoPautaIdRoute
  '/agentes': typeof AuthenticatedAgentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agentes': typeof AuthenticatedAgentesRouteWithChildren
  '/_authenticated/curadoria': typeof AuthenticatedCuradoriaRoute
  '/_authenticated/perfis': typeof AuthenticatedPerfisRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/agentes/$agente': typeof AuthenticatedAgentesAgenteRoute
  '/_authenticated/aprovacao/$pautaId': typeof AuthenticatedAprovacaoPautaIdRoute
  '/_authenticated/agentes/': typeof AuthenticatedAgentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agentes'
    | '/curadoria'
    | '/perfis'
    | '/pipeline'
    | '/agentes/$agente'
    | '/aprovacao/$pautaId'
    | '/agentes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/curadoria'
    | '/perfis'
    | '/pipeline'
    | '/agentes/$agente'
    | '/aprovacao/$pautaId'
    | '/agentes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agentes'
    | '/_authenticated/curadoria'
    | '/_authenticated/perfis'
    | '/_authenticated/pipeline'
    | '/_authenticated/agentes/$agente'
    | '/_authenticated/aprovacao/$pautaId'
    | '/_authenticated/agentes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfis': {
      id: '/_authenticated/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof AuthenticatedPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curadoria': {
      id: '/_authenticated/curadoria'
      path: '/curadoria'
      fullPath: '/curadoria'
      preLoaderRoute: typeof AuthenticatedCuradoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes': {
      id: '/_authenticated/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AuthenticatedAgentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes/': {
      id: '/_authenticated/agentes/'
      path: '/'
      fullPath: '/agentes/'
      preLoaderRoute: typeof AuthenticatedAgentesIndexRouteImport
      parentRoute: typeof AuthenticatedAgentesRoute
    }
    '/_authenticated/aprovacao/$pautaId': {
      id: '/_authenticated/aprovacao/$pautaId'
      path: '/aprovacao/$pautaId'
      fullPath: '/aprovacao/$pautaId'
      preLoaderRoute: typeof AuthenticatedAprovacaoPautaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes/$agente': {
      id: '/_authenticated/agentes/$agente'
      path: '/$agente'
      fullPath: '/agentes/$agente'
      preLoaderRoute: typeof AuthenticatedAgentesAgenteRouteImport
      parentRoute: typeof AuthenticatedAgentesRoute
    }
  }
}

interface AuthenticatedAgentesRouteChildren {
  AuthenticatedAgentesAgenteRoute: typeof AuthenticatedAgentesAgenteRoute
  AuthenticatedAgentesIndexRoute: typeof AuthenticatedAgentesIndexRoute
}

const AuthenticatedAgentesRouteChildren: AuthenticatedAgentesRouteChildren = {
  AuthenticatedAgentesAgenteRoute: AuthenticatedAgentesAgenteRoute,
  AuthenticatedAgentesIndexRoute: AuthenticatedAgentesIndexRoute,
}

const AuthenticatedAgentesRouteWithChildren =
  AuthenticatedAgentesRoute._addFileChildren(AuthenticatedAgentesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentesRoute: typeof AuthenticatedAgentesRouteWithChildren
  AuthenticatedCuradoriaRoute: typeof AuthenticatedCuradoriaRoute
  AuthenticatedPerfisRoute: typeof AuthenticatedPerfisRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedAprovacaoPautaIdRoute: typeof AuthenticatedAprovacaoPautaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentesRoute: AuthenticatedAgentesRouteWithChildren,
  AuthenticatedCuradoriaRoute: AuthenticatedCuradoriaRoute,
  AuthenticatedPerfisRoute: AuthenticatedPerfisRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedAprovacaoPautaIdRoute: AuthenticatedAprovacaoPautaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
